---
- name: Test connection my server
  become: yes
  become_user: root
  hosts: tr

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Ping my server
      ping: 
      

