---
- name: setup Mysql with demo_db and remote login
  become: yes
  hosts: tr

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Copy SQL file
      copy:
        src: table_data.sql
        dest: /tmp/table_data.sql
        

    - name: Import SQL file into database
      mysql_db:
        name: expo
        state: import  #dump
        target: /tmp/table_data.sql
        login_user: root
        login_password: "{{root_password}}"
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted