---
- name: copy files
  become: yes
  become_user: root
  hosts: tr


  vars_files:
    - vars.yml


  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes


    - name: Create a directory if it does not exist
      file:
        path: /var/www/trur
        state: directory
        mode: 0777


    - name: Copy php vars_files
      copy:
        src: files/truruki/tphp/index.php
        dest: /var/www/trur/index.php
        owner: root
        group: root
        mode: 0777
